#-- A PV for the big volume we're managing w/ this recycler instance
apiVersion: v1
kind: PersistentVolume
metadata:
  name: glustersupervol-testvol
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  glusterfs:
    endpoints: glusterfs-cluster
    path: testvol
    readOnly: false
  claimRef:
    name: glustersupervol-testvol
    namespace: glusterfs

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: glustersupervol-testvol
  namespace: glusterfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  volumeName: glustersupervol-testvol

---

#-- apps/v1beta2 for k8s 1.8+
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: volrecycler-testvol
  namespace: glusterfs
spec:
  selector:
    matchLabels:
      gluster-subvol-recycler: testvol
  #-- Replicas must be 1. We don't support multiple recyclers for the same
  #-- supervolume
  replicas: 1
  strategy:
    #-- On update, kill all the old then create the new
    type: Recreate
  template:
    metadata:
      labels:
        gluster-subvol-recycler: testvol
      namespace: glusterfs
    spec:
      containers:
      - name: volrecycler
        image: johnstrunk/gluster-subvol-volrecycler:latest
        imagePullPolicy: Always
        args:
        #-- This needs to match the volume mountpoint
        - "/data"
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: data
          mountPath: /data
      serviceAccount: volrecycler-sa
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: glustersupervol-testvol
